// Marathon Pilates liability waiver — single source of truth.
//
// Ported verbatim from the studio's existing Arketa waiver (the legal text
// clients already sign). When the client acknowledges it at intake, we record
// WAIVER_VERSION alongside the timestamp + typed signature, so we always know
// which wording a given client agreed to. If the text is ever revised, bump
// WAIVER_VERSION so consent records stay unambiguous.

export const WAIVER_VERSION = 'v1-2024'

export const WAIVER_TITLE = 'Liability Waiver Release'

export const WAIVER_TEXT = `LIVE WELL PILATES, LLC d/b/a MARATHON PILATES (“Company”) LIABILITY RELEASE (“Release”)

In consideration of my use of the health or fitness products, equipment, facilities, advice, and services provided by Company (“Activity”), which I acknowledge is good and sufficient consideration, I hereby agree as follows:

1. Activity. I acknowledge that I desire to participate in the Activity and that my participation in the Activity is governed by this Release. I hereby certify that all of the information listed in this Release is true and correct. I understand, agree to, and acknowledge the following:

• My participation in the Activity may expose me to the coronavirus disease 2019 (COVID-19) and/or other infections. I expressly assume the risk of exposure to the same. I agree to take all possible self-protective measures, including wearing a facemask and regularly washing my hands.

• Activity details are subject to change in Company’ sole discretion and it does not endorse, recommend or promote any product or therapy.

• Participation in the Activity involves strenuous physical activity and I am healthy enough to engage in such activity. I have no medical or physical conditions which could interfere with my safety in the Activity. Alternatively, I am willing to assume any and all risks that may be created, directly or indirectly, by any such condition and my participation in the Activity. Company shall have no obligation to monitor my health before, during or after the Activity.

• Participation in the Activity may expose me to certain risks, which may include injury to the musculoskeletal and/or cardio respiratory systems which can result in serious injury or death, injury or death due to negligence on the part of myself or other participants, injury or death due to improper use or failure of equipment, or injury or death due to a medical condition.

• I will not operate equipment in a negligent, improper, unsafe or unlawful manner.

• It is my sole responsibility to participate in exercises that are appropriate for the current status of my health. If I have any questions or concerns about whether or not a particular activity is appropriate to my current health status, I understand it is my responsibility to ask my doctor if the Activity is appropriate before I participate, and Company strongly recommends you do so.

• I have adequate insurance to cover any injury or damage I may cause or suffer while participating in the Activity, or I agree to bear the cost of such injury or damage. I am either more than eighteen (18) years of age, an emancipated minor, or possess legal parental or guardian consent, and am fully able and competent to enter into this Release.

2. Compliance with Laws / Policies. I agree that I will comply and maintain my behavior in accordance with all applicable laws including but not limited to, observation of all safety regulations during the Activity, applicable rules and regulations of Company and its parents and affiliated companies and networks (collectively, the “Activity Entities”), the Activity Entities’ policies, procedures, rules and regulations and generally accepted social practices, in connection with participation in the Activity. I understand and agree that the Activity Entities each have the right, in their sole discretion, to disqualify and remove me from any activity at any time if my behavior at any point is uncooperative, disruptive or may or does cause damage to the person, property or the reputation of an Activity Entity or otherwise violates the policies of an Activity Entity.

3. Assumption of Risk. I acknowledge the possibility of adverse physical changes during an exercise program, including abnormal blood pressure, fainting, heart disorders, stroke, and in very rare instances, heart attack or even death. I fully understand the Activity can involve known and unanticipated risks which could result in bodily injury, illness, death, damage or loss to myself, my property, and to other third parties and their property, which may be caused by my own actions or inactions, those of others participating in the Activity, or the negligence or misconduct of any of the Released Parties named below; and I fully accept and assume all such risks and all responsibility for losses, costs, and damages I or any third parties incur as a result of my participation in the Activity. I further represent that I am participating in the Activity voluntarily, without having been coerced or convinced by the activity entities or any other party to do so and with full knowledge, appreciation and understanding of the dangers and personal risks involved, and that I am in good health, physically fit and otherwise prepared and able to participate in the Activity.

4. Liability Release. I, ON BEHALF OF MYSELF, MY HEIRS, ASSIGNS, EXECUTORS, ADMINISTRATORS, AND ANY OTHERS WHO MAY TAKE BY OR THROUGH ME, HEREBY REPRESENT AND COVENANT NOT TO SUE OR BRING ANY LAWSUIT OR MAKE ANY CLAIM UNDER ANY THEORY AND HEREBY UNCONDITIONALLY AND IRREVOCABLY WAIVE, RELEASE AND FOREVER DISCHARGE THE ACTIVITY ENTITIES AND EACH OF THEIR RESPECTIVE PARENTS, SUBSIDIARIES, AFFILIATES, EQUIPMENT LESSORS, AND THE OFFICERS, DIRECTORS, MEMBERS, MANAGERS, EMPLOYEES, REPRESENTATIVES AND AGENTS (COLLECTIVELY, “RELEASED PARTIES”) FROM AND AGAINST ANY AND ALL CLAIMS, DEMANDS, LOSSES, COSTS, EXPENSES, FEES (INCLUDING ATTORNEYS’ FEES), CAUSES OF ACTION AND LIABILITIES OF ANY NATURE WHATSOEVER, WHICH I MAY NOW HAVE OR WHICH MAY ARISE, OR HEREAFTER BE ENTITLED TO ASSERT, UNDER ANY THEORY WHATSOEVER (IN TORT, CONTRACT, BY STATUTE, OR OTHERWISE) AGAINST EACH OR ANY OF THEM, FOR ANY MATTER, CAUSE OR THING, ANY INJURY, NEGLIGENCE, LOSS OR DAMAGE OF ANY KIND, INCLUDING, WITHOUT LIMITATION, FAILURE TO DIAGNOSE OR IDENTIFY ILLNESS, ANY DEATH, LOSS, INJURY, DAMAGE, OR ACCIDENT TO PERSON(S) OR PROPERTY, OR LOSS OF ENJOYMENT, OR OTHER HARM OR LOSS OF ANY NATURE WHATSOEVER, WHETHER DIRECT, COMPENSATORY, EXEMPLARY, INCIDENTAL OR CONSEQUENTIAL, ARISING FROM OR IN CONNECTION WITH, DIRECTLY OR INDIRECTLY, THE ACTIVITY, THE ACCEPTANCE, POSSESSION, DELIVERY, MISDELIVERY, USE OR MISUSE OF EQUIPMENT, AND/OR THE RIGHTS GRANTED HEREUNDER, INCLUDING WITHOUT LIMITATION, MY PREPARATION FOR OR PARTICIPATION IN THE ACTIVITY OR ANY ADVICE PROVIDED BY THE RELEASED PARTIES, WHETHER OR NOT CAUSED, IN WHOLE OR IN PART, BY THE ACTS, OMISSIONS, NEGLIGENCE OR MISCONDUCT OF ANY RELEASED PARTY.

5. Indemnification. WITH REGARD TO ANY CLAIM, LOSS, LIABILITY, COST OR EXPENSE ARISING OUT OF: (I) ANY ACTUAL, ANTICIPATED OR THREATENED BREACH OF ANY WARRANTY, REPRESENTATION OR UNDERTAKING MADE BY ME IN THIS RELEASE; (II) MY PARTICIPATION AND APPEARANCE IN THE ACTIVITY; AND, (III) IF THE UNDERSIGNED IS A MINOR, THE MINOR’S DISAFFIRMANCE OF THIS RELEASE, I (AND, IF APPLICABLE THE UNDERSIGNED PARENT(S) AND/OR GUARDIAN(S)) IRREVOCABLY AGREE TO DEFEND, INDEMNIFY AND HOLD THE RELEASED PARTIES HARMLESS FROM AND AGAINST SUCH CLAIM, LOSS, LIABILITY, COST AND EXPENSE, INCLUDING REASONABLE LEGAL COSTS AND ATTORNEYS’ FEES.

6. No Warranties and Limitation of Liability. I AGREE THE ACTIVITY AND ANY PRODUCTS, SERVICES, ADVICE OR TESTS INCIDENTAL TO THE SAME ARE PROVIDED AS-IS WITHOUT ANY WARRANTY, REPRESENTATION, OR GUARANTEE, EXPRESS OR IMPLIED, IN FACT OR IN LAW, WHETHER NOW KNOWN OR HEREINAFTER ENACTED, RELATIVE TO THE USE OR PARTICIPATION IN THE ACTIVITY, INCLUDING THEIR ACCURACY, QUALITY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR THE ABSENCE OF SIDE EFFECTS. BY PARTICIPATING IN THE ACTIVITY, I AGREE THAT TO THE EXTENT PERMITTED BY APPLICABLE LAW: (1) ANY AND ALL CLAIMS, JUDGMENTS AND AWARDS WILL BE LIMITED TO ACTUAL THIRD-PARTY, OUT-OF-POCKET COSTS INCURRED (IF ANY) NOT TO EXCEED TEN DOLLARS ($10.00), BUT IN NO EVENT WILL ATTORNEYS’ FEES BE AWARDED OR RECOVERABLE; AND (2) UNDER NO CIRCUMSTANCES WILL ANY PARTICIPANT BE PERMITTED TO OBTAIN ANY AWARD FOR, AND PARTICIPANT HEREBY KNOWINGLY AND EXPRESSLY WAIVES ALL RIGHTS TO SEEK, PUNITIVE, INCIDENTAL, CONSEQUENTIAL OR SPECIAL DAMAGES, LOST PROFITS AND/OR ANY OTHER DAMAGES, OTHER THAN ACTUAL OUT OF POCKET EXPENSES NOT TO EXCEED TEN DOLLARS ($10.00), AND/OR ANY RIGHTS TO HAVE DAMAGES MULTIPLIED OR OTHERWISE INCREASED. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATIONS OR EXCLUSION OF LIABILITY, SO THE ABOVE MAY NOT APPLY TO YOU.

7. Miscellaneous. I understand and agree that this Release is governed by and construed in accordance with the laws of the State of Tennessee without giving effect or regard to any principles or doctrines of conflicts of law. Any action arising out of or relating to the Activity or this Release must be filed exclusively in the federal or state courts in Maury County, Tennessee, and I hereby consent to the personal jurisdiction of such courts, and any right to a trial by jury is hereby waived. I understand that my participation in the Activity is subject to applicable laws and to all terms, conditions, and restrictions relating to the Activity imposed by the Activity Entities and this Release. If any provision hereof shall be invalid or unenforceable due to any law, said provision shall be modified to the minimum extent necessary to effect compliance with such law, and in any event such invalidity or unenforceability shall have no effect upon the remaining terms and conditions hereof. I acknowledge that the rights and remedies granted to me herein are intended to be solely for my benefit and shall not otherwise be deemed to confer upon or give to any third party any remedy, claim, cause of action or other right. The rights and remedies granted the Activity Entities herein shall inure to the benefit of the Activity Entities, their licensees, successors, and assigns.

8. Complete Release. I UNDERSTAND AND AGREE THAT THIS IS A COMPLETE RELEASE OF ALL CLAIMS AND RIGHTS OF THE UNDERSIGNED AGAINST THE ACTIVITY ENTITIES AND THAT NO ACTION WILL BE TAKEN BY ME OR ON MY BEHALF WITH RESPECT OF ANY SUCH RIGHTS.

9. Acknowledgements. I HAVE READ, FULLY UNDERSTAND, AND AGREE WITH ALL OF THE ABOVE. I ACKNOWLEDGE THAT THE TERMS OF THIS RELEASE ARE CONTRACTUAL AND ARE NOT BY WAY OF RECITAL. I ACKNOWLEDGE AND UNDERSTAND THAT THIS RELEASE HAS BEEN PREPARED BY AN ATTORNEY AND THAT COMPANY RECOMMENDS I CONSULT WITH AN ATTORNEY IN CONNECTION WITH THIS RELEASE. I REPRESENT AND WARRANT I HAVE BEEN GIVEN A REASONABLE OPPORTUNITY TO DISCUSS THIS RELEASE WITH COUNSEL OF MY CHOICE AND THAT I HAVE HAD AMPLE OPPORTUNITY TO INVESTIGATE ALL THE MATTERS INVOLVED IN EXECUTING THIS RELEASE. I FURTHER PROMISE THAT I AM FULLY AUTHORIZED TO EXECUTE THIS RELEASE AND THAT I HAVE DULY AND VALIDLY EXECUTED THIS RELEASE OF MY OWN FREE WILL.`
