-- Cache for AI-generated dashboard nudge copy (Ruby's brand voice).
--
-- Why a table: the nudge line is generated by Claude per (client, service). We
-- cache it so (a) we don't pay for / wait on a model call on every dashboard
-- load, and (b) the client sees the SAME line each visit instead of a freshly
-- reworded sentence every refresh (which would feel flickery). The route
-- regenerates only when the cached row is missing or stale.
--
-- One row per (client, service). Writes happen ONLY through the service-role
-- route POST /api/nudge-copy — there is intentionally no client INSERT/UPDATE
-- policy. Clients never query this table directly (the route returns the line
-- to them), so no client SELECT policy is needed either. Staff/owner may read
-- it for debugging. service_role bypasses RLS, so the route can read+write.
--
-- Run in the Supabase SQL editor. Safe to run repeatedly.

CREATE TABLE IF NOT EXISTS public.nudge_copy (
  client_id   uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  service_key text NOT NULL,
  message     text NOT NULL,
  model       text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (client_id, service_key)
);

ALTER TABLE public.nudge_copy ENABLE ROW LEVEL SECURITY;

-- Staff/owner read for debugging. No client policies + no write policies by
-- design — only the service-role route touches this table.
DROP POLICY IF EXISTS "Staff read nudge copy" ON public.nudge_copy;
CREATE POLICY "Staff read nudge copy"
  ON public.nudge_copy
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND profiles.role IN ('owner', 'admin', 'manager')
    )
  );
